// US States Tax Information - Sales tax data for all 50 states + DC
// Based on 2025 tax requirements

const US_STATES_TAX_INFO = {
  AL: { name: 'Alabama', hasStateTax: true, stateRate: 0.04, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 250000, transactions: null }, marketplaceFacilitator: true, sst: true, note: 'Simplified Seller Use Tax (SSUT) program available' },
  AK: { name: 'Alaska', hasStateTax: false, stateRate: 0, filingTypes: ['local'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: false, note: 'No state tax, but must collect for ARSSTC member localities' },
  AZ: { name: 'Arizona', hasStateTax: true, stateRate: 0.056, filingTypes: ['state', 'county', 'city'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: false, note: 'TPT license required' },
  AR: { name: 'Arkansas', hasStateTax: true, stateRate: 0.065, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  CA: { name: 'California', hasStateTax: true, stateRate: 0.0725, filingTypes: ['state', 'district'], reportFormat: 'district', nexusThreshold: { sales: 500000, transactions: null }, marketplaceFacilitator: true, sst: false, note: 'Highest threshold - $500K sales required' },
  CO: { name: 'Colorado', hasStateTax: true, stateRate: 0.029, filingTypes: ['state', 'county', 'city', 'special'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: false, note: 'Home rule cities (Denver, Aurora, etc.) require separate registration' },
  CT: { name: 'Connecticut', hasStateTax: true, stateRate: 0.0635, shippingTaxable: true, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: false },
  DE: { name: 'Delaware', hasStateTax: false, stateRate: 0, filingTypes: [], reportFormat: 'none', nexusThreshold: null, marketplaceFacilitator: false, sst: false, note: 'No sales tax' },
  FL: { name: 'Florida', hasStateTax: true, stateRate: 0.06, filingTypes: ['state', 'county'], reportFormat: 'county', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: false },
  GA: { name: 'Georgia', hasStateTax: true, stateRate: 0.04, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  HI: { name: 'Hawaii', hasStateTax: true, stateRate: 0.04, shippingTaxable: true, filingTypes: ['state', 'county'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: false, note: 'GET (Gross Excise Tax) not traditional sales tax - applies to seller' },
  ID: { name: 'Idaho', hasStateTax: true, stateRate: 0.06, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: true },
  IL: { name: 'Illinois', hasStateTax: true, stateRate: 0.0625, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: false, note: 'ROT (Retailers Occupation Tax) - multiple local taxes' },
  IN: { name: 'Indiana', hasStateTax: true, stateRate: 0.07, shippingTaxable: true, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  IA: { name: 'Iowa', hasStateTax: true, stateRate: 0.06, filingTypes: ['state', 'local'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: true },
  KS: { name: 'Kansas', hasStateTax: true, stateRate: 0.065, shippingTaxable: true, filingTypes: ['state', 'county', 'city'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: true },
  KY: { name: 'Kentucky', hasStateTax: true, stateRate: 0.06, shippingTaxable: true, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  LA: { name: 'Louisiana', hasStateTax: true, stateRate: 0.0445, filingTypes: ['state', 'parish'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: false, note: 'Parish taxes filed through Louisiana Sales Tax Commission' },
  ME: { name: 'Maine', hasStateTax: true, stateRate: 0.055, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: false },
  MD: { name: 'Maryland', hasStateTax: true, stateRate: 0.06, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: false, note: 'Annual report & LLC fees required separately' },
  MA: { name: 'Massachusetts', hasStateTax: true, stateRate: 0.0625, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: false },
  MI: { name: 'Michigan', hasStateTax: true, stateRate: 0.06, shippingTaxable: true, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  MN: { name: 'Minnesota', hasStateTax: true, stateRate: 0.06875, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  MS: { name: 'Mississippi', hasStateTax: true, stateRate: 0.07, shippingTaxable: true, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 250000, transactions: null }, marketplaceFacilitator: true, sst: false },
  MO: { name: 'Missouri', hasStateTax: true, stateRate: 0.04225, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: false },
  MT: { name: 'Montana', hasStateTax: false, stateRate: 0, filingTypes: [], reportFormat: 'none', nexusThreshold: null, marketplaceFacilitator: false, sst: false, note: 'No sales tax' },
  NE: { name: 'Nebraska', hasStateTax: true, stateRate: 0.055, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  NV: { name: 'Nevada', hasStateTax: true, stateRate: 0.0685, filingTypes: ['state', 'county'], reportFormat: 'county', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  NH: { name: 'New Hampshire', hasStateTax: false, stateRate: 0, filingTypes: [], reportFormat: 'none', nexusThreshold: null, marketplaceFacilitator: false, sst: false, note: 'No sales tax' },
  NJ: { name: 'New Jersey', hasStateTax: true, stateRate: 0.06625, shippingTaxable: true, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  NM: { name: 'New Mexico', hasStateTax: true, stateRate: 0.05125, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: false, note: 'Gross Receipts Tax (GRT) - not traditional sales tax' },
  NY: { name: 'New York', hasStateTax: true, stateRate: 0.04, shippingTaxable: true, filingTypes: ['state', 'county', 'city'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 500000, transactions: 100 }, marketplaceFacilitator: true, sst: false, note: 'High threshold - $500K AND 100+ transactions required' },
  NC: { name: 'North Carolina', hasStateTax: true, stateRate: 0.0475, shippingTaxable: true, filingTypes: ['state', 'county'], reportFormat: 'county', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  ND: { name: 'North Dakota', hasStateTax: true, stateRate: 0.05, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: true },
  OH: { name: 'Ohio', hasStateTax: true, stateRate: 0.0575, shippingTaxable: true, filingTypes: ['state', 'county'], reportFormat: 'county', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  OK: { name: 'Oklahoma', hasStateTax: true, stateRate: 0.045, filingTypes: ['state', 'county', 'city'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: true },
  OR: { name: 'Oregon', hasStateTax: false, stateRate: 0, filingTypes: [], reportFormat: 'none', nexusThreshold: null, marketplaceFacilitator: false, sst: false, note: 'No sales tax' },
  PA: { name: 'Pennsylvania', hasStateTax: true, stateRate: 0.06, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: false, note: 'Philadelphia & Allegheny County have additional local taxes' },
  RI: { name: 'Rhode Island', hasStateTax: true, stateRate: 0.07, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  SC: { name: 'South Carolina', hasStateTax: true, stateRate: 0.06, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: true },
  SD: { name: 'South Dakota', hasStateTax: true, stateRate: 0.045, shippingTaxable: true, filingTypes: ['state', 'municipal'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true, note: 'Origin of Wayfair decision' },
  TN: { name: 'Tennessee', hasStateTax: true, stateRate: 0.07, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: true },
  TX: { name: 'Texas', hasStateTax: true, stateRate: 0.0625, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 500000, transactions: null }, marketplaceFacilitator: true, sst: false, note: 'High threshold - $500K sales required' },
  UT: { name: 'Utah', hasStateTax: true, stateRate: 0.0485, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  VT: { name: 'Vermont', hasStateTax: true, stateRate: 0.06, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  VA: { name: 'Virginia', hasStateTax: true, stateRate: 0.043, filingTypes: ['state', 'local'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: false },
  WA: { name: 'Washington', hasStateTax: true, stateRate: 0.065, shippingTaxable: true, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: true, note: 'B&O tax also applies to some sellers' },
  WV: { name: 'West Virginia', hasStateTax: true, stateRate: 0.06, shippingTaxable: true, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  WI: { name: 'Wisconsin', hasStateTax: true, stateRate: 0.05, shippingTaxable: true, filingTypes: ['state', 'county'], reportFormat: 'county', nexusThreshold: { sales: 100000, transactions: null }, marketplaceFacilitator: true, sst: true },
  WY: { name: 'Wyoming', hasStateTax: true, stateRate: 0.04, filingTypes: ['state', 'local'], reportFormat: 'jurisdiction', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: true },
  DC: { name: 'District of Columbia', hasStateTax: true, stateRate: 0.06, shippingTaxable: true, filingTypes: ['state'], reportFormat: 'standard', nexusThreshold: { sales: 100000, transactions: 200 }, marketplaceFacilitator: true, sst: false },
};

// State-specific filing formats - defines exact fields needed for each state's return
// Based on actual state filing requirements as of 2025
const STATE_FILING_FORMATS = {
  WV: {
    name: 'West Virginia',
    formName: 'WV/CST-200CU (Combined Sales & Use Tax Return)',
    website: 'https://mytaxes.wvtax.gov/',
    fields: [
      { name: 'Line 1 - Gross Sales', key: 'grossSales', description: 'Total gross receipts/sales' },
      { name: 'Line 2 - Deductions', key: 'deductions', description: 'Non-taxable sales, exemptions' },
      { name: 'Line 3 - Net Taxable Sales', key: 'taxableSales', description: 'Line 1 minus Line 2' },
      { name: 'Line 4 - Tax Rate', key: 'taxRate', description: '6.0%' },
      { name: 'Line 5 - Tax Due', key: 'taxDue', description: 'Line 3 × 0.06' },
      { name: 'Line 6 - Tax Collected', key: 'taxCollected', description: 'Actual tax collected from customers' },
    ],
    calculate: (data) => ({
      grossSales: data.totalSales || data.sales || 0,
      deductions: 0,
      taxableSales: data.totalSales || data.sales || 0,
      taxRate: '6.0%',
      taxDue: (data.totalSales || data.sales || 0) * 0.06,
      taxCollected: data.taxOwed || data.tax || 0,
    }),
  },
  PA: {
    name: 'Pennsylvania',
    formName: 'PA-100 Sales, Use and Hotel Occupancy Tax Return',
    website: 'https://www.revenue.pa.gov/OnlineServices/myPATH/',
    fields: [
      { name: 'Line 1 - Gross Sales', key: 'grossSales', description: 'Total sales price of taxable goods' },
      { name: 'Line 2 - Sales Not Subject to Tax', key: 'exemptSales', description: 'Exempt sales (resale, manufacturing, etc.)' },
      { name: 'Line 3 - Net Taxable Sales', key: 'taxableSales', description: 'Line 1 minus Line 2' },
      { name: 'Line 4 - State Tax (6%)', key: 'stateTax', description: 'Line 3 × 0.06' },
      { name: 'Line 5 - Local Tax (if applicable)', key: 'localTax', description: 'Philadelphia 2%, Allegheny 1%' },
      { name: 'Line 6 - Total Tax Due', key: 'totalTax', description: 'Line 4 + Line 5' },
    ],
    note: 'Philadelphia adds 2% local tax, Allegheny County (Pittsburgh) adds 1%. Most remote sellers only owe state 6%.',
    calculate: (data) => ({
      grossSales: data.totalSales || data.sales || 0,
      exemptSales: 0,
      taxableSales: data.totalSales || data.sales || 0,
      stateTax: (data.totalSales || data.sales || 0) * 0.06,
      localTax: 0,
      totalTax: data.taxOwed || data.tax || 0,
    }),
  },
  MD: {
    name: 'Maryland',
    formName: 'Form 202 - Sales and Use Tax Return',
    website: 'https://interactive.marylandtaxes.gov/',
    fields: [
      { name: 'Line 1 - Gross Sales', key: 'grossSales', description: 'Total sales of tangible personal property' },
      { name: 'Line 2 - Exempt Sales', key: 'exemptSales', description: 'Sales for resale, exempt organizations' },
      { name: 'Line 3 - Net Taxable Sales', key: 'taxableSales', description: 'Line 1 minus Line 2' },
      { name: 'Line 4 - Tax Collected (6%)', key: 'taxCollected', description: 'Tax collected from customers' },
    ],
    note: 'Maryland has a single 6% rate statewide. No local taxes for remote sellers.',
    calculate: (data) => ({
      grossSales: data.totalSales || data.sales || 0,
      exemptSales: 0,
      taxableSales: data.totalSales || data.sales || 0,
      taxCollected: data.taxOwed || data.tax || 0,
    }),
  },
  VA: {
    name: 'Virginia',
    formName: 'Form ST-9 - Retail Sales and Use Tax Return',
    website: 'https://www.tax.virginia.gov/',
    fields: [
      { name: 'Line 1 - Gross Sales', key: 'grossSales', description: 'Total gross sales' },
      { name: 'Line 2 - Deductions', key: 'deductions', description: 'Exempt sales, sales for resale' },
      { name: 'Line 3 - Taxable Sales', key: 'taxableSales', description: 'Line 1 minus Line 2' },
      { name: 'Line 4a - State Tax (4.3%)', key: 'stateTax', description: 'Line 3 × 0.043' },
      { name: 'Line 4b - Local Tax (1%)', key: 'localTax', description: 'Line 3 × 0.01' },
      { name: 'Line 5 - Total Tax (5.3%)', key: 'totalTax', description: 'Line 4a + Line 4b' },
    ],
    note: 'Virginia has combined 5.3% rate (4.3% state + 1% local). Some areas have additional regional taxes.',
    calculate: (data) => ({
      grossSales: data.totalSales || data.sales || 0,
      deductions: 0,
      taxableSales: data.totalSales || data.sales || 0,
      stateTax: (data.totalSales || data.sales || 0) * 0.043,
      localTax: (data.totalSales || data.sales || 0) * 0.01,
      totalTax: data.taxOwed || data.tax || 0,
    }),
  },
  TX: {
    name: 'Texas',
    formName: 'Form 01-117 - Texas Sales and Use Tax Return',
    website: 'https://comptroller.texas.gov/taxes/sales/',
    fields: [
      { name: 'Item 1 - Total Sales', key: 'totalSales', description: 'Total receipts from all sales' },
      { name: 'Item 2 - Taxable Sales', key: 'taxableSales', description: 'Sales subject to sales tax' },
      { name: 'Item 3 - Taxable Purchases', key: 'taxablePurchases', description: 'Use tax on purchases (usually $0)' },
      { name: 'Item 4 - Total Tax Due', key: 'totalTax', description: 'State (6.25%) + Local taxes' },
    ],
    note: 'Texas has 6.25% state rate. Local taxes vary by location (up to 2% additional). Report location of delivery for local tax.',
    calculate: (data) => ({
      totalSales: data.totalSales || data.sales || 0,
      taxableSales: data.totalSales || data.sales || 0,
      taxablePurchases: 0,
      totalTax: data.taxOwed || data.tax || 0,
    }),
  },
  FL: {
    name: 'Florida',
    formName: 'Form DR-15 - Sales and Use Tax Return',
    website: 'https://floridarevenue.com/taxes/taxesfees/Pages/sales_tax.aspx',
    fields: [
      { name: 'Line 1 - Gross Sales', key: 'grossSales', description: 'Total gross sales' },
      { name: 'Line 2 - Exempt Sales', key: 'exemptSales', description: 'Tax-exempt sales' },
      { name: 'Line 3 - Taxable Amount', key: 'taxableSales', description: 'Line 1 minus Line 2' },
      { name: 'Line 4 - State Tax (6%)', key: 'stateTax', description: 'Line 3 × 0.06' },
      { name: 'Line 5 - County Surtax', key: 'surtax', description: 'Discretionary sales surtax (varies by county)' },
      { name: 'Line 6 - Total Tax Due', key: 'totalTax', description: 'Line 4 + Line 5' },
    ],
    note: 'Florida has 6% state rate plus county surtax (0-2.5%). Use customer shipping address to determine county.',
    calculate: (data) => ({
      grossSales: data.totalSales || data.sales || 0,
      exemptSales: 0,
      taxableSales: data.totalSales || data.sales || 0,
      stateTax: (data.totalSales || data.sales || 0) * 0.06,
      surtax: 0,
      totalTax: data.taxOwed || data.tax || 0,
    }),
  },
  CA: {
    name: 'California',
    formName: 'CDTFA-401 - State, Local, and District Sales and Use Tax Return',
    website: 'https://onlineservices.cdtfa.ca.gov/',
    fields: [
      { name: 'Line 1 - Total Gross Sales', key: 'grossSales', description: 'Total of all sales' },
      { name: 'Line 2 - Purchases Subject to Use Tax', key: 'useTaxPurchases', description: 'Usually $0 for sellers' },
      { name: 'Line 3 - Total', key: 'totalSubject', description: 'Line 1 + Line 2' },
      { name: 'Line 4 - Deductions', key: 'deductions', description: 'Nontaxable sales, exempt sales' },
      { name: 'Line 5 - Total Taxable', key: 'taxableSales', description: 'Line 3 minus Line 4' },
      { name: 'Line 6 - Tax Due', key: 'taxDue', description: 'Based on district tax rates' },
    ],
    note: 'CA requires district-level reporting. Base rate is 7.25% but varies by district (7.25%-10.75%). Use CDTFA online system.',
    calculate: (data) => ({
      grossSales: data.totalSales || data.sales || 0,
      useTaxPurchases: 0,
      totalSubject: data.totalSales || data.sales || 0,
      deductions: 0,
      taxableSales: data.totalSales || data.sales || 0,
      taxDue: data.taxOwed || data.tax || 0,
    }),
  },
  NY: {
    name: 'New York',
    formName: 'Form ST-100 - New York State and Local Sales and Use Tax Return',
    website: 'https://www.tax.ny.gov/bus/st/stidx.htm',
    fields: [
      { name: 'Part 1 - Gross Sales', key: 'grossSales', description: 'Gross sales and services' },
      { name: 'Part 1 - Non-Taxable Sales', key: 'nonTaxable', description: 'Exempt sales, clothing under $110' },
      { name: 'Part 1 - Taxable Sales', key: 'taxableSales', description: 'Gross minus non-taxable' },
      { name: 'Part 2 - State Tax (4%)', key: 'stateTax', description: 'Taxable × 0.04' },
      { name: 'Part 2 - Local Tax', key: 'localTax', description: 'Varies by jurisdiction (0-4.875%)' },
      { name: 'Total Tax Due', key: 'totalTax', description: 'State + Local' },
    ],
    note: 'NY exempts clothing/footwear under $110. NYC has 4.5% local tax. Use Schedule H for jurisdiction breakdown.',
    calculate: (data) => ({
      grossSales: data.totalSales || data.sales || 0,
      nonTaxable: 0,
      taxableSales: data.totalSales || data.sales || 0,
      stateTax: (data.totalSales || data.sales || 0) * 0.04,
      localTax: 0,
      totalTax: data.taxOwed || data.tax || 0,
    }),
  },
  OH: {
    name: 'Ohio',
    formName: 'UST 1 - Universal Sales Tax Return',
    website: 'https://tax.ohio.gov/sales_and_use.aspx',
    fields: [
      { name: 'Line 1 - Gross Receipts', key: 'grossSales', description: 'Total gross receipts' },
      { name: 'Line 2 - Exempt Sales', key: 'exemptSales', description: 'Non-taxable transactions' },
      { name: 'Line 3 - Net Taxable Sales', key: 'taxableSales', description: 'Line 1 minus Line 2' },
      { name: 'Line 4 - Tax Collected', key: 'taxCollected', description: 'Total tax collected' },
    ],
    note: 'Ohio has 5.75% state rate plus county taxes (0.75%-2.25%). Use county of delivery.',
    calculate: (data) => ({
      grossSales: data.totalSales || data.sales || 0,
      exemptSales: 0,
      taxableSales: data.totalSales || data.sales || 0,
      taxCollected: data.taxOwed || data.tax || 0,
    }),
  },
  NC: {
    name: 'North Carolina',
    formName: 'Form E-500 - Sales and Use Tax Return',
    website: 'https://www.ncdor.gov/taxes-forms/sales-and-use-tax',
    fields: [
      { name: 'Line 1 - Gross Receipts', key: 'grossSales', description: 'Total gross receipts' },
      { name: 'Line 2 - Exempt Receipts', key: 'exemptSales', description: 'Tax-exempt sales' },
      { name: 'Line 3 - Net Taxable Sales', key: 'taxableSales', description: 'Line 1 minus Line 2' },
      { name: 'Line 4 - State Tax (4.75%)', key: 'stateTax', description: 'Line 3 × 0.0475' },
      { name: 'Line 5 - Local Tax (2-2.75%)', key: 'localTax', description: 'County tax rate varies' },
      { name: 'Line 6 - Total Tax', key: 'totalTax', description: 'Line 4 + Line 5' },
    ],
    note: 'NC has 4.75% state + 2-2.75% county. Combined rates range 6.75%-7.5%. Use destination county.',
    calculate: (data) => ({
      grossSales: data.totalSales || data.sales || 0,
      exemptSales: 0,
      taxableSales: data.totalSales || data.sales || 0,
      stateTax: (data.totalSales || data.sales || 0) * 0.0475,
      localTax: 0,
      totalTax: data.taxOwed || data.tax || 0,
    }),
  },
  GA: {
    name: 'Georgia',
    formName: 'Form ST-3 - Sales and Use Tax Return',
    website: 'https://gtc.dor.ga.gov/',
    fields: [
      { name: 'Line 1 - Gross Sales', key: 'grossSales', description: 'Gross sales, use, and withdrawals' },
      { name: 'Line 2 - Deductions', key: 'deductions', description: 'Exempt and non-taxable sales' },
      { name: 'Line 3 - Taxable Sales', key: 'taxableSales', description: 'Line 1 minus Line 2' },
      { name: 'Line 4 - State Tax (4%)', key: 'stateTax', description: 'Line 3 × 0.04' },
      { name: 'Line 5 - Local Tax', key: 'localTax', description: 'LOST/SPLOST varies by jurisdiction' },
      { name: 'Line 6 - Total Tax', key: 'totalTax', description: 'Line 4 + Line 5' },
    ],
    note: 'GA has 4% state rate + 3-4% local option taxes. Combined rates 7-9%. File through Georgia Tax Center.',
    calculate: (data) => ({
      grossSales: data.totalSales || data.sales || 0,
      deductions: 0,
      taxableSales: data.totalSales || data.sales || 0,
      stateTax: (data.totalSales || data.sales || 0) * 0.04,
      localTax: 0,
      totalTax: data.taxOwed || data.tax || 0,
    }),
  },
  NJ: {
    name: 'New Jersey',
    formName: 'Form ST-50 - Sales and Use Tax Return',
    website: 'https://www.state.nj.us/treasury/taxation/su.shtml',
    fields: [
      { name: 'Line 1 - Gross Receipts', key: 'grossSales', description: 'Total gross receipts' },
      { name: 'Line 2 - Non-Taxable Sales', key: 'exemptSales', description: 'Exempt sales' },
      { name: 'Line 3 - Taxable Sales', key: 'taxableSales', description: 'Line 1 minus Line 2' },
      { name: 'Line 4 - Tax Due (6.625%)', key: 'taxDue', description: 'Line 3 × 0.06625' },
    ],
    note: 'NJ has single statewide 6.625% rate. No local taxes. Urban Enterprise Zones may have reduced rates.',
    calculate: (data) => ({
      grossSales: data.totalSales || data.sales || 0,
      exemptSales: 0,
      taxableSales: data.totalSales || data.sales || 0,
      taxDue: data.taxOwed || data.tax || 0,
    }),
  },
  // Generic format for states without specific config
  OK: {
    name: 'Oklahoma',
    formName: 'Form STS 20002 - Sales Tax Return',
    website: 'https://oktap.tax.ok.gov/',
    requiresJurisdictions: true,  // Flag for jurisdiction-level reporting
    jurisdictionType: 'county',
    fields: [
      { name: 'State Tax (4.5%)', key: 'stateTax', description: 'Total state tax collected' },
      { name: 'County/City Taxes', key: 'localTax', description: 'Breakdown by jurisdiction required' },
      { name: 'Total Tax Due', key: 'totalTax', description: 'State + Local' },
    ],
    note: 'Oklahoma requires county/city breakdown. Use OkTAP portal to report by jurisdiction. Local rates vary (0-6.5% additional).',
    calculate: (data, stateInfo) => ({
      stateTax: (data.totalSales || data.sales || 0) * 0.045,
      localTax: (data.taxOwed || data.tax || 0) - ((data.totalSales || data.sales || 0) * 0.045),
      totalTax: data.taxOwed || data.tax || 0,
    }),
    exportFormat: 'jurisdiction', // Triggers jurisdiction-level CSV export
  },
  CO: {
    name: 'Colorado',
    formName: 'DR 0100 - Colorado Retail Sales Tax Return',
    website: 'https://mytax.colorado.gov/',
    requiresJurisdictions: true,
    jurisdictionType: 'city/county',
    fields: [
      { name: 'State Tax (2.9%)', key: 'stateTax', description: 'State sales tax' },
      { name: 'RTD/CD/FD Taxes', key: 'specialTax', description: 'Regional transit, cultural, football district taxes' },
      { name: 'County Taxes', key: 'countyTax', description: 'Breakdown by county' },
      { name: 'City/Local Taxes', key: 'cityTax', description: 'Home rule cities require separate filing!' },
      { name: 'Total Tax Due', key: 'totalTax', description: 'All taxes' },
    ],
    note: 'Colorado home rule cities (Denver, Aurora, Colorado Springs, etc.) require SEPARATE registration and filing directly with the city. State-administered localities can be filed together.',
    calculate: (data, stateInfo) => ({
      stateTax: (data.totalSales || data.sales || 0) * 0.029,
      specialTax: 0,
      countyTax: 0,
      cityTax: (data.taxOwed || data.tax || 0) - ((data.totalSales || data.sales || 0) * 0.029),
      totalTax: data.taxOwed || data.tax || 0,
    }),
    exportFormat: 'jurisdiction',
  },
  KS: {
    name: 'Kansas',
    formName: 'ST-36 - Retailers Sales Tax Return',
    website: 'https://www.ksrevenue.gov/custservsalestax.html',
    requiresJurisdictions: true,
    jurisdictionType: 'jurisdiction',
    fields: [
      { name: 'Gross Sales', key: 'grossSales', description: 'Total sales' },
      { name: 'Exempt Sales', key: 'exemptSales', description: 'Non-taxable sales' },
      { name: 'Taxable Sales', key: 'taxableSales', description: 'Gross minus exempt' },
      { name: 'Tax by Jurisdiction', key: 'jurisdictionTax', description: 'Breakdown by city/county' },
    ],
    note: 'Kansas requires jurisdiction-level reporting. Use StreamlinedSalesTax.org or the Kansas WebFile system.',
    calculate: (data, stateInfo) => ({
      grossSales: data.totalSales || data.sales || 0,
      exemptSales: 0,
      taxableSales: data.totalSales || data.sales || 0,
      jurisdictionTax: data.taxOwed || data.tax || 0,
    }),
    exportFormat: 'jurisdiction',
  },
  LA: {
    name: 'Louisiana',
    formName: 'R-1029 - Louisiana Sales Tax Return',
    website: 'https://latap.revenue.louisiana.gov/',
    requiresJurisdictions: true,
    jurisdictionType: 'parish',
    fields: [
      { name: 'State Tax (4.45%)', key: 'stateTax', description: 'State sales tax' },
      { name: 'Parish Taxes', key: 'parishTax', description: 'Local parish taxes (vary widely)' },
      { name: 'Total Tax Due', key: 'totalTax', description: 'State + Parish' },
    ],
    note: 'Louisiana requires parish-level reporting. Remote sellers can use the Louisiana Sales & Use Tax Commission single return for most parishes.',
    calculate: (data, stateInfo) => ({
      stateTax: (data.totalSales || data.sales || 0) * 0.0445,
      parishTax: (data.taxOwed || data.tax || 0) - ((data.totalSales || data.sales || 0) * 0.0445),
      totalTax: data.taxOwed || data.tax || 0,
    }),
    exportFormat: 'jurisdiction',
  },
  DEFAULT: {
    name: 'Standard',
    formName: 'State Sales Tax Return',
    website: null,
    fields: [
      { name: 'Gross Sales', key: 'grossSales', description: 'Total sales shipped to state' },
      { name: 'Exempt Sales', key: 'exemptSales', description: 'Non-taxable sales' },
      { name: 'Net Taxable Sales', key: 'taxableSales', description: 'Gross minus exempt' },
      { name: 'Tax Collected', key: 'taxCollected', description: 'Tax you collected on orders' },
    ],
    calculate: (data, stateInfo) => ({
      grossSales: data.totalSales || data.sales || 0,
      exemptSales: 0,
      taxableSales: data.totalSales || data.sales || 0,
      taxCollected: data.taxOwed || data.tax || 0,
    }),
  },
};

export { US_STATES_TAX_INFO, STATE_FILING_FORMATS };
