/* eslint-disable react-refresh/only-export-components */
import React, { useState } from 'react';
import { Printer, Download, X, FileText, Loader2 } from 'lucide-react';

// Print button that opens a print-friendly version of the current view
const PrintButton = ({ title, onPrint, className = '' }) => (
  <button
    onClick={onPrint}
    className={`px-3 py-1.5 bg-slate-700 hover:bg-slate-600 rounded-lg text-sm text-white flex items-center gap-2 transition-colors ${className}`}
    title="Print / Save as PDF"
  >
    <Printer className="w-4 h-4" />
    <span className="hidden sm:inline">Print</span>
  </button>
);

// Generate a printable HTML document and open in a new window
const printView = ({ title, storeName, dateRange, content, styles = '' }) => {
  const win = window.open('', '_blank');
  if (!win) {
    alert('Please allow popups to print reports');
    return;
  }

  const html = `<!DOCTYPE html>
<html>
<head>
  <title>${title} - ${storeName || 'Dashboard'}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1e293b; padding: 40px; max-width: 1100px; margin: 0 auto; }
    h1 { font-size: 24px; font-weight: 700; margin-bottom: 4px; }
    h2 { font-size: 18px; font-weight: 600; margin: 24px 0 12px; color: #334155; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; }
    h3 { font-size: 14px; font-weight: 600; color: #475569; margin: 16px 0 8px; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 3px solid #6366f1; }
    .header-left .store-name { font-size: 28px; font-weight: 800; color: #1e293b; }
    .header-left .report-title { font-size: 16px; color: #64748b; margin-top: 2px; }
    .header-right { text-align: right; color: #94a3b8; font-size: 12px; }
    .kpi-row { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 24px; }
    .kpi-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; }
    .kpi-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #94a3b8; margin-bottom: 4px; }
    .kpi-value { font-size: 24px; font-weight: 700; color: #1e293b; }
    .kpi-sub { font-size: 12px; color: #64748b; margin-top: 2px; }
    .positive { color: #059669; }
    .negative { color: #dc2626; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }
    th { background: #f1f5f9; text-align: left; padding: 8px 12px; font-weight: 600; color: #475569; border-bottom: 2px solid #e2e8f0; }
    td { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; }
    tr:nth-child(even) { background: #fafafa; }
    .text-right { text-align: right; }
    .text-center { text-align: center; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
    .section { margin-bottom: 24px; }
    .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
    .badge-green { background: #dcfce7; color: #166534; }
    .badge-red { background: #fef2f2; color: #991b1b; }
    .badge-amber { background: #fefce8; color: #854d0e; }
    @media print {
      body { padding: 20px; }
      .no-print { display: none !important; }
      .kpi-row { grid-template-columns: repeat(4, 1fr); }
    }
    ${styles}
  </style>
</head>
<body>
  <div class="no-print" style="background:#6366f1;color:white;padding:12px 20px;margin:-40px -40px 24px;display:flex;justify-content:space-between;align-items:center;">
    <span style="font-weight:600;">Print Preview — ${title}</span>
    <div>
      <button onclick="window.print()" style="background:white;color:#6366f1;border:none;padding:8px 16px;border-radius:6px;font-weight:600;cursor:pointer;margin-right:8px;">🖨️ Print / Save PDF</button>
      <button onclick="window.close()" style="background:rgba(255,255,255,0.2);color:white;border:none;padding:8px 16px;border-radius:6px;cursor:pointer;">✕ Close</button>
    </div>
  </div>
  <div class="header">
    <div class="header-left">
      <div class="store-name">${storeName || 'Dashboard Report'}</div>
      <div class="report-title">${title}</div>
    </div>
    <div class="header-right">
      ${dateRange ? `<div>${dateRange}</div>` : ''}
      <div>Generated ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</div>
    </div>
  </div>
  ${content}
  <div class="footer">
    Generated by Tallowbourn Dashboard • ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}
  </div>
</body>
</html>`;

  win.document.write(html);
  win.document.close();
};

// ── Helper functions for building report content ──

const formatCurr = (v) => {
  if (v == null || isNaN(v)) return '$0.00';
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 2 }).format(v);
};

const formatPct = (v) => {
  if (v == null || isNaN(v)) return '0%';
  return (v * 100).toFixed(1) + '%';
};

const pctClass = (v) => v >= 0 ? 'positive' : 'negative';

const kpiCard = (label, value, sub = '') => `
  <div class="kpi-card">
    <div class="kpi-label">${label}</div>
    <div class="kpi-value">${value}</div>
    ${sub ? `<div class="kpi-sub">${sub}</div>` : ''}
  </div>
`;

const tableRow = (cells, isHeader = false) => {
  const tag = isHeader ? 'th' : 'td';
  return `<tr>${cells.map(c => {
    const align = typeof c === 'object' ? (c.align || '') : '';
    const val = typeof c === 'object' ? c.value : c;
    const cls = typeof c === 'object' ? (c.className || '') : '';
    return `<${tag} class="${align} ${cls}">${val}</${tag}>`;
  }).join('')}</tr>`;
};

// ── Report generators for each view ──

export const printProfitability = ({ storeName, allDaysData, allWeeksData, savedCogs, dateRange }) => {
  const weeks = Object.keys(allWeeksData).sort();
  const totalRevenue = weeks.reduce((s, w) => s + (allWeeksData[w]?.total?.revenue || 0), 0);
  const totalAdSpend = weeks.reduce((s, w) => s + (allWeeksData[w]?.total?.adSpend || 0), 0);
  const totalCogs = weeks.reduce((s, w) => s + (allWeeksData[w]?.total?.cogs || 0), 0);
  const totalProfit = weeks.reduce((s, w) => s + (allWeeksData[w]?.total?.netProfit || 0), 0);
  const margin = totalRevenue > 0 ? totalProfit / totalRevenue : 0;

  let weeklyRows = weeks.slice(-12).map(w => {
    const d = allWeeksData[w]?.total || {};
    const m = d.revenue > 0 ? (d.netProfit || 0) / d.revenue : 0;
    return tableRow([
      w,
      { value: formatCurr(d.revenue), align: 'text-right' },
      { value: formatCurr(d.cogs || 0), align: 'text-right' },
      { value: formatCurr(d.adSpend || 0), align: 'text-right' },
      { value: formatCurr(d.netProfit || 0), align: 'text-right', className: pctClass(d.netProfit) },
      { value: formatPct(m), align: 'text-right', className: pctClass(m) },
    ]);
  }).join('');

  const content = `
    <div class="kpi-row">
      ${kpiCard('Total Revenue', formatCurr(totalRevenue), `${weeks.length} weeks`)}
      ${kpiCard('Total COGS', formatCurr(totalCogs), `${Object.keys(savedCogs).length} SKUs tracked`)}
      ${kpiCard('Ad Spend', formatCurr(totalAdSpend), `${totalRevenue > 0 ? (totalAdSpend/totalRevenue*100).toFixed(1) : 0}% of revenue`)}
      ${kpiCard('Net Profit', formatCurr(totalProfit), `<span class="${pctClass(margin)}">${formatPct(margin)} margin</span>`)}
    </div>
    <h2>Weekly P&L (Last 12 Weeks)</h2>
    <table>
      ${tableRow(['Week', { value: 'Revenue', align: 'text-right' }, { value: 'COGS', align: 'text-right' }, { value: 'Ad Spend', align: 'text-right' }, { value: 'Net Profit', align: 'text-right' }, { value: 'Margin', align: 'text-right' }], true)}
      ${weeklyRows}
    </table>
  `;

  printView({ title: 'Profitability & P&L Report', storeName, dateRange, content });
};

export const printInventory = ({ storeName, invHistory, savedCogs, appSettings }) => {
  const latestDate = Object.keys(invHistory).sort().pop();
  if (!latestDate) return;
  const snapshot = invHistory[latestDate];
  const products = snapshot?.products || snapshot?.items || [];
  
  const critDays = appSettings?.inventoryDaysCritical || 14;
  const lowDays = appSettings?.inventoryDaysLow || 30;

  let rows = products.map(p => {
    const daysLeft = p.daysOfInventory || p.daysRemaining || 0;
    const qty = p.quantity || p.availableQuantity || 0;
    const health = qty === 0 ? 'Out of Stock' : daysLeft <= critDays ? 'Critical' : daysLeft <= lowDays ? 'Low' : 'OK';
    const badge = health === 'OK' ? 'badge-green' : health === 'Low' ? 'badge-amber' : 'badge-red';
    return tableRow([
      p.sku || p.asin || '—',
      p.productName || p.title || '—',
      { value: qty.toLocaleString(), align: 'text-right' },
      { value: daysLeft > 0 ? `${daysLeft}d` : '—', align: 'text-right' },
      { value: `<span class="badge ${badge}">${health}</span>`, align: 'text-center' },
    ]);
  }).join('');

  const totalUnits = products.reduce((s, p) => s + (p.quantity || p.availableQuantity || 0), 0);
  const critical = products.filter(p => (p.quantity || p.availableQuantity || 0) === 0 || (p.daysOfInventory || p.daysRemaining || 0) <= critDays).length;

  const content = `
    <div class="kpi-row">
      ${kpiCard('Snapshot Date', latestDate)}
      ${kpiCard('Total SKUs', products.length.toString())}
      ${kpiCard('Total Units', totalUnits.toLocaleString())}
      ${kpiCard('Critical Items', `<span class="${critical > 0 ? 'negative' : 'positive'}">${critical}</span>`)}
    </div>
    <h2>Inventory Details</h2>
    <table>
      ${tableRow(['SKU', 'Product', { value: 'Qty', align: 'text-right' }, { value: 'Days Left', align: 'text-right' }, { value: 'Status', align: 'text-center' }], true)}
      ${rows}
    </table>
  `;

  printView({ title: 'Inventory Report', storeName, dateRange: `Snapshot: ${latestDate}`, content });
};

export const printSalesTax = ({ storeName, salesTaxConfig }) => {
  const { nexusStates = {}, filingHistory = {} } = salesTaxConfig || {};
  const states = Object.entries(nexusStates).filter(([, c]) => c?.hasNexus);

  let rows = states.map(([code, config]) => {
    const freq = config.frequency || 'monthly';
    const regId = config.registrationId || '—';
    const filings = filingHistory[code] || {};
    const filedCount = Object.values(filings).filter(f => f?.filed).length;
    return tableRow([code, freq, regId, { value: filedCount.toString(), align: 'text-right' }]);
  }).join('');

  const content = `
    <div class="kpi-row">
      ${kpiCard('Nexus States', states.length.toString())}
      ${kpiCard('Total Filings', Object.values(filingHistory).reduce((s, h) => s + Object.values(h).filter(f => f?.filed).length, 0).toString())}
      ${kpiCard('Monthly', states.filter(([, c]) => (c.frequency || 'monthly') === 'monthly').length.toString())}
      ${kpiCard('Quarterly', states.filter(([, c]) => c.frequency === 'quarterly').length.toString())}
    </div>
    <h2>Nexus States</h2>
    <table>
      ${tableRow(['State', 'Frequency', 'Registration ID', { value: 'Filings', align: 'text-right' }], true)}
      ${rows}
    </table>
  `;

  printView({ title: 'Sales Tax Summary', storeName, content });
};

export const printDailySummary = ({ storeName, allDaysData, dateRange }) => {
  const days = Object.keys(allDaysData).sort().slice(-30);
  
  let rows = days.map(d => {
    const day = allDaysData[d];
    const amzRev = day?.amazon?.revenue || 0;
    const shopRev = day?.shopify?.revenue || 0;
    const totalRev = amzRev + shopRev;
    const adSpend = (day?.amazon?.adSpend || 0) + (day?.shopify?.googleSpend || 0) + (day?.shopify?.metaSpend || 0);
    return tableRow([
      d,
      { value: formatCurr(amzRev), align: 'text-right' },
      { value: formatCurr(shopRev), align: 'text-right' },
      { value: formatCurr(totalRev), align: 'text-right' },
      { value: formatCurr(adSpend), align: 'text-right' },
    ]);
  }).join('');

  const totalRev = days.reduce((s, d) => s + (allDaysData[d]?.amazon?.revenue || 0) + (allDaysData[d]?.shopify?.revenue || 0), 0);
  const totalAds = days.reduce((s, d) => s + (allDaysData[d]?.amazon?.adSpend || 0) + (allDaysData[d]?.shopify?.googleSpend || 0) + (allDaysData[d]?.shopify?.metaSpend || 0), 0);

  const content = `
    <div class="kpi-row">
      ${kpiCard('Days', days.length.toString())}
      ${kpiCard('Total Revenue', formatCurr(totalRev))}
      ${kpiCard('Avg Daily', formatCurr(totalRev / (days.length || 1)))}
      ${kpiCard('Total Ad Spend', formatCurr(totalAds))}
    </div>
    <h2>Daily Breakdown (Last 30 Days)</h2>
    <table>
      ${tableRow(['Date', { value: 'Amazon', align: 'text-right' }, { value: 'Shopify', align: 'text-right' }, { value: 'Total', align: 'text-right' }, { value: 'Ad Spend', align: 'text-right' }], true)}
      ${rows}
    </table>
  `;

  printView({ title: 'Daily Sales Report', storeName, dateRange: dateRange || `${days[0]} – ${days[days.length - 1]}`, content });
};

export { PrintButton, printView };
